### ISSUE TITLE
Unable to comment with link

### ISSUE THREAD

**Issue by jsmueller7** [recogito/recogito-client#289]
I've just tried with client version `1.1.2`: I've not been able to comment or reply using the link insertion function. Also tested on the staging server.

**Comment by rsimon** [comment]
Hi @jsmueller7,

can you describe what happens? Does the popup close as soon as you click the link button? (If so: that sounds like a regression in the base text annotator library - which however should be fixed in v1.1.2, so it might be a deployment problem, with a stuck library version?)

If not: does it happen in text (PDF vs. txt/TEI) or in both interfaces (text + image). Also, can you confirm which staging system you are testing on? (I can't seem to reproduce this on ours at http://recogito-staging.covecollective.org.)

**Comment by jsmueller7** [comment]
Hi @rsimon,

when I mark a text section and klick the link symbol, the popup "Link" opens. After pasting an URL and sending I return to the regular - but empty - annotation editor. This happens with all text formats (I haven't tested on images). It also happens on the PS staging server. That's why I believe it could be a general problem.

I've just tested with another approach: I inserted the URL and then I added some whitespaces and removed them - this way I was able to create a link comment. Unfortunatelly I haven't been able to succeed with this workaround twice... Still trying to find a pattern.

**Comment by jsmueller7** [comment]
The one time I was able to create the link I was on the PS staging server. Still I can't reproduce.
In my german UI also the `Link` label went missing, just like with `e-mail` in the invitation pop up.

**Comment by jsmueller7** [comment]
Allright. Now I've been able to reproduce the workaround: I simply need to insert the link twice, without leaving the annotation editor inbetween. So the workaround at the moment is:

* Mark a text or image section,
* Open the link editor,
* paste an URL,
* return to the empty annotation editor,
* again start the link insertion,
* now you'll have a hyperlink.

**Comment by rsimon** [comment]
Ah, ok I think I know what's going on. The feature "works as designed", in a sense (but isn't really designed right...)

The link button is supposed to add a link to an existing text snippet. It will only work if you have text selected in the comment box. I.e. let's say:
- You write the text "Here's a link to example.com"
- You select "example.com" and click the link button
- You paste the link "https://www.example.com" into the URL popup and click "Save"
- The comment now shows "Here's a link to [example.com]" - with "example.com" as a clickable link

What __does not__ happen is that a link without prior selected text is just pasted as a clickable URL. (I.e. I'm pretty sure that pasting https://www.example.com WITHOUT having text selected does not currently do anything - which is, what I believe you have been doing?).

But fully agreed that this should be a supported/expected behavior. I can look into it!

**Comment by jsmueller7** [comment]
🤔 ...it seems that the workaround I posted before isn't waterproof. And yes, I can confirm that some activity in the annotation editor seems to helm with creating URLs. The process you describe also doesn't work, at least it doesn't work reliably.

**Comment by rsimon** [comment]
Let's definitely do a screen-share session on this in the next call. Something else must be going on if my described process fails in your case. (I haven't seen any issues with it yet. But, as always, there can be edge conditions we've missed so far...)

**Comment by jsmueller7** [comment]
Let's do that. Maybe I'll find out how this (not) works by then...

**Comment by jsmueller7** [comment]
🤦‍♂️ OK - So I finally get how this feature is supposed to work. If I select text in the annotation editor and then create an hyperlink it works.

**Comment by rsimon** [comment]
Yes, exactly, that's what I meant :-)

But, I'm in full agreement. The UX right now is super confusing. The link just getting dropped with no feedback is not what should happen. (But, rather, the link should be added to the comment "as is", but clickable.) Shouldn't be a big fix - I'll look into it.

**Comment by jsmueller7** [comment]
I've started working with the Linking feature in my own corse and I think that it's a very good feature. Besides of the missing label I'm also missing a possibility to insert links after I've made an annotation. Including links makes me swich a lot between browser tabs.

**Comment by rsimon** [comment]
I'm already working on a PR. This fixes the problem with not being able to paste links without a selection, and the missing label. 

Hah - indeed. When editing an existing annotation, the context menu button stays on, and the rich text editor controls are not coming back up. I'll look into this, too!
