### ISSUE TITLE
Text Annotator: Popup should be moved to a Portal and not be a child of the text container

### ISSUE THREAD

**Issue by lwjameson** [recogito/recogito-client#72]

**Comment by rsimon** [comment]
Sent you a message on Slack. Looks like this is working now? 

Also: did a little digging in my code. There's a reason for why this isn't currently a Portal: in the current design, the popup will automatically scroll along with the text (because it's a child of the scrollable text container). If we change to a portal, scroll needs to be handled via JavaScript, making things significantly more complex. I.e. unless there's a good reason, I'm advocating to stick with the current implementation.
